### PR TITLE
Gradle 4 gradle example fixes

### LINKED ISSUE #95: gradle-examples/4/gradle-example needs newer gradle-wrapper, 2.0 fails
This project declares a very old Gradle (2.0) in its wrapper and does not work:

```
* What went wrong:
Failed to notify build listener.
> Could not find method getPluginManager() for arguments [] on root project 'gradle-example'.
> Could not find method getPluginManager() for arguments [] on root project 'gradle-example'.
> Could not find method getPluginManager() for arguments [] on root project 'gradle-example'.
> Could not find method getPluginManager() for arguments [] on root project 'gradle-example'.
> Could not find method getPluginManager() for arguments [] on root project 'gradle-example'.
```

Should upgrade to latest Gradle 4.3.1.

Build failure in Travis: https://travis-ci.org/javabrett/project-examples/builds/306531512
Improved build failure in Travis (resolves this issue), exposes new issue: https://travis-ci.org/javabrett/project-examples/builds/306532953

### PR DESCRIPTION
**Pull request by javabrett**
Make this project build by bumping the Gradle (via wrapper) version to current 4.3.1, and making the project resolve via jcenter in the example.

Fixes #95.

### CODE REVIEW

**Comment by eyalbe4** [comment]
Thank you for this pull request @javabrett.
It is probably best to resolve your build dependencies from a virtual repository in Artifactory, which also includes jcenter. This way, you enjoy the benefits for having your dependencies cached in Artifactory for faster builds.
We might however need to improve the examples documentation, so that it includes setup instructions, on how to create and configure the virtual repository in the gradle script.
In addition, can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge your code?

**Comment by javabrett** [comment]
My aim here was to provide a simple path whereby the (example) project can actually build/run - acting as a kind of integration-test for itself.  In order to do that, it requires a repo to resolve.  This could be either `jcenter` or a local repo set-up for the integration-test.

On second thoughts, maybe a local Docker container would do.

To be clear - the goal here was to validate the example project code itself, that is, create an integration-style test for the example project, so that it is certain that it works.

**Comment by eyalbe4** [comment]
@javabrett,
We've just pushed [this](https://github.com/JFrogDev/project-examples/commit/e1c4a1f0b054db008da3a7a76ba3a9f82366832a) commit, which updates the wrapper version for all gradle examples. 
Thanks again for noticing and suggesting this change.

**Comment by javabrett** [comment]
Thanks for the global `gradlew` version-bump.

Remaining question - is it desirable for this (example) project to build-from-source (some task, maybe `build`) for the purposes of:

1. Developer-friendliness - expect an example project to be able to perform a basic build straight-up without modification.
2. Allow this example to have its own basic-check CI build.

Currently even `build` requires a local Artifactory instance or it will error-out on dependency-resolution.  If it pointed to `jcenter` it would at least build.  Of course `artifactoryPublish` would require a local instance.

**Comment by eyalbe4** [comment]
@javabrett,
What if we tale the existing *gradle-example-minimal* example, and use it to create an additional new example named *gradle-example-jcenter-resolution*? The new example will be similar to *gradle-example-minimal*, but will resolve all if its dependencies from *jcenter*.
Let me know what you think.

**Comment by javabrett** [comment]
My motivation was - given the 11 example v4 Gradle projects (and perhaps apply to other example categories) - how many of them are valid over-time, pass a smoke-test build e.g. `./gradlew build`.  No `artifactoryPublish` or anything that would definitely invoke the need to push to a local Artifactory.

Adding a [`.travis.yml`](https://github.com/javabrett/project-examples/commit/413f8a051b84e77f6ed957724c530ed2ac4e5959) answers that - [4 of 11 can build](https://travis-ci.org/javabrett/project-examples/builds/319004683) that way.

Glancing at the failures there's a bit of a mixture: local environment assumption/config, dependency-resolution (via non-existent local Artifactory), Gradle syntax-errors??, missing Gradle Wrapper scripts etc.

Maybe `build` is expecting too much of these in some/most cases ...

**Comment by Georg-M** [comment]
That conflicting file (`gradle-examples/4/gradle-example/build.gradle`) became a problem for me.
See my [comment](https://github.com/JFrogDev/project-examples/issues/36#issuecomment-365415461) for Issue #36.
Maybe this can help.

**Comment by javabrett** [comment]
Rebased to current `master`.  With the PR, `./gradlew clean build` passes, without it fails because artifacts are expected to be pulled from a local Artifactory, which might not be running -> use JCenter.

**Comment by Georg-M** [comment]
@javabrett 
It seems, I haven't any problem with resolving.
[build.gradle](https://github.com/JFrogDev/project-examples/blob/master/gradle-examples/gradle-example/build.gradle) file is original from master, without fixed #96
[Jenkinsfile](https://github.com/JFrogDev/project-examples/blob/master/jenkins-pipeline-examples/gradle-example/Jenkinsfile) has original setting from master:
`rtGradle.resolver repo:'jcenter', server: server`
And I hadn't errors from resolving procedures.

I see a problem in the folders' tree in GitHub repository.
Jenkins Pipeline uses this directory tree to build -
(1) workspace for Jenkins Job and (2) workspace for Gradle
Current path to `build.gradle` (in master) is:
`gradle-examples/gradle-example/build.gradle`
But current Jenkinsfile (in master) is setting another path:
`gradle-examples/4/gradle-example/build.gradle`
This is configured in the Jenkinsfile step:
`rtGradle.run rootDir: "gradle-examples/4/gradle-example/", buildFile: 'build.gradle', ...`

Maybe you mean that
directory tree on `https://jcenter.bintray.com` differs from
directory tree on `https://github.com/JFrogDev/project-examples` ?

I am new with Gradle and Artifactory, but I know how Jenkins and Pipeline work.
So, my notes can look little bit stupid. Sorry.

**Comment by Georg-M** [comment]
It is possible, that `'localhost'` is not correctly resolved by DNS in your case (?)
I had similar problem with Artifactory Web GUI.

My simple deployment is a VBox VM with two docker containers with Jenkins and Artifactory.
All necessary ports were published on VM and on my workstation (via VBox NAT network).
Address `http://localhost:8081/` was accessible from workstation only by **Firefox** browser.
**Chrome** couldn't access neither `http://localhost:8081/` nor `http://127.0.0.1:8081/`.
I didn't try IPv6 variants.
Mr.Google found possible solution for my case: Don't use `'localhost'`.
After I've added second network interface with static IP to the VM, the issue was fixed.
New address `http://192.168.50.103:8081/` is accessible from both browsers now.

**Comment by javabrett** [comment]
Right, I saw your unrelated issue over on #36.

This issue here is about whether a simple example project `gradle-examples/gradle-example` should require a local Artifactory instance to work and demostrate the project building and resolving artifacts.  Currently it does.  This change would allow it to resolve via Jcenter instead, then the build works.

**Comment by Georg-M** [comment]
@javabrett, yes, you are right.
Thank you.

**Comment by eyalbe4** [comment]
@javabrett,
I suggest we modify the existing *gradle-jcenter-resolve* example in this repository, to be identical to the *gradle-example* project, except for one change - the resolution would be done directly from jcenter - which is the change you suggested here.
I suggest we leave however the *gradle-example* project as is, so that it can be used to resolve dependencies from Artifactory, allowing you take advantage of the built in caching Artifactory provides.

**Comment by javabrett** [comment]
OK, closing this.  My sole interest in a lot of these changes was for the example-project to be immediately-buildable, without any additional infrastructure e.g. a local Artifactory deployed and running.  That way the example project can be verified in a basic way - there could even be a simple CI build for the example projects, to ensure that they don't break.

**Pull request closed without merging**
